version: "3"
services:
  redis:
    image: redis
    restart: always
    container_name: redis
    privileged: true
    ports:
      - "6379:6379"
    networks:
      - net-pongo
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
    command:
        redis-server /etc/redis/redis.conf --appendonly yes --requirepass wazhHcz52cchC1IlUF
  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    container_name: rabbitmq-m1
    privileged: true
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net-pongo
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq/m1/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw
      - ./rabbitmq/m1/rabbitmq:/var/lib/rabbitmq:rw
    command:
        redis-server /etc/redis/redis.conf --appendonly yes --requirepass wazhHcz52cchC1IlUF
 
  mysql:
    image: mysql:5.6
    restart: always
    container_name: mysql
    privileged: true
    ports:
      - "3306:3306"
    networks:
      - net-pongo
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: 'front_ssp_user'
      MYSQL_PASS: 'Uu6weCM3dgSPtyqd'
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf/my.cnf:/etc/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=mysql_native_password
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
      --max_connections=3600
    user: root

  ssp:
    image: 900528/php-fpm-nginx-alpine:latest
    restart: always
    container_name: ssp
    privileged: true
    ports:
      - "80:80"
    networks:
      - net-pongo
    volumes:
      - ./ssp:/usr/share/nginx/html
      - ./nginx/conf.d/ci.conf:/etc/nginx/conf.d/default.conf
    environment:
      CI_ENV: "development"
    extra_hosts:
      - "front_ssp_cache_redis_m01:172.18.0.1"
      - "front_ssp_mysql_s01:172.18.0.1"
      - "front_ssp_mysql_s02:172.18.0.1"
      - "www_valueq_affiliate_mysql_m01:172.18.0.1"
      - "front_ssp_mysql_s01:172.18.0.1"
      - "middle_user_mysql_s01:172.18.0.1"

  gw:
    image: 900528/php-fpm-nginx-alpine:latest
    restart: always
    container_name: gw
    privileged: true
    ports:
    - "8080:80"
    networks:
    - net-pongo
    volumes:
    - ./gw:/usr/share/nginx/html
    - ./nginx/conf.d/ci.conf:/etc/nginx/conf.d/default.conf
    environment:
      CI_ENV: "development"
    extra_hosts:
      - "middle_gw_cache_redis_m01:172.18.0.1"
      - "middle_gw_mysql_m01:172.18.0.1"
      - "middle_gw_mysql_s01:172.18.0.1"
      - "middle_gw_mysql_s02:172.18.0.1"
      - "www_valueq_affiliate_mysql_s01:172.18.0.1"

networks:
  net-pongo:
    driver: bridge
